// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/vucongthanh92/courier/chat-service/config"
	"github.com/vucongthanh92/courier/chat-service/database"
	"github.com/vucongthanh92/courier/chat-service/internal/api"
	"github.com/vucongthanh92/courier/chat-service/internal/api/cron"
	"github.com/vucongthanh92/courier/chat-service/internal/api/grpc"
	"github.com/vucongthanh92/courier/chat-service/internal/api/http"
	"github.com/vucongthanh92/courier/chat-service/internal/api/http/v1"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/persistent/conversation"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/persistent/member"
	conversation2 "github.com/vucongthanh92/courier/chat-service/internal/usecase/conversation"
	"github.com/vucongthanh92/courier/chat-service/redis"
)

// Injectors from wire.go:

func InitializeContainer(appCfg *config.AppConfig, readDb *database.GormReadDb, writeDb *database.GormWriteDb, redisClient redis.Client) *api.ApiContainer {
	conversationQueryRepoI := conversation.InitConversationQueryRepo(readDb, writeDb)
	conversationServiceI := conversation2.InitConversationUsecase(conversationQueryRepoI)
	conversationHandler := v1.InitConversationHandler(conversationServiceI)
	server := http.NewServer(appCfg, conversationHandler)
	grpcServer := grpc.NewServer(appCfg)
	cronServer := cron.NewServer(appCfg)
	apiContainer := api.NewApiContainer(server, grpcServer, cronServer)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(api.NewApiContainer)

var apiSet = wire.NewSet(cron.NewServer, grpc.NewServer, http.NewServer)

var handlerSet = wire.NewSet(v1.InitConversationHandler)

var serviceSet = wire.NewSet(conversation2.InitConversationUsecase)

var repoSet = wire.NewSet(member.InitMemberCommandRepo, member.InitMemberQueryRepo, conversation.InitConversationCommandRepo, conversation.InitConversationQueryRepo)
