// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/vucongthanh92/courier/chat-service/config"
	"github.com/vucongthanh92/courier/chat-service/database"
	"github.com/vucongthanh92/courier/chat-service/helper/transaction"
	"github.com/vucongthanh92/courier/chat-service/internal/api"
	"github.com/vucongthanh92/courier/chat-service/internal/api/cron"
	"github.com/vucongthanh92/courier/chat-service/internal/api/grpc"
	"github.com/vucongthanh92/courier/chat-service/internal/api/http"
	"github.com/vucongthanh92/courier/chat-service/internal/api/http/v1"
	"github.com/vucongthanh92/courier/chat-service/internal/api/ws"
	"github.com/vucongthanh92/courier/chat-service/internal/domain/interfaces"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/external/kafka"
	redis2 "github.com/vucongthanh92/courier/chat-service/internal/repository/external/redis"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/external/user_grpc"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/persistent/conversation"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/persistent/member"
	"github.com/vucongthanh92/courier/chat-service/internal/repository/persistent/message"
	conversation2 "github.com/vucongthanh92/courier/chat-service/internal/usecase/conversation"
	member2 "github.com/vucongthanh92/courier/chat-service/internal/usecase/member"
	message2 "github.com/vucongthanh92/courier/chat-service/internal/usecase/message"
	"github.com/vucongthanh92/courier/chat-service/internal/worker"
	"github.com/vucongthanh92/courier/chat-service/redis"
	"github.com/vucongthanh92/go-base-utils/logger"
)

// Injectors from wire.go:

func InitializeContainer(appCfg *config.AppConfig, readDb *database.GormReadDb, writeDb *database.GormWriteDb, redisClient redis.Client) *api.ApiContainer {
	conversationQueryRepoI := conversation.InitConversationQueryRepo(readDb, writeDb)
	conversationCommandRepoI := conversation.InitConversationCommandRepo(readDb, writeDb)
	memberCmdRepoI := member.InitMemberCommandRepo(readDb, writeDb)
	memberQueryRepoI := member.InitMemberQueryRepo(readDb, writeDb)
	userGrpcClient := user_grpc.NewGrpcClient(appCfg)
	managerTxn := transaction.InitManagerTxn(writeDb)
	chatEventPublisherI := kafka.InitChatEventPublisher(appCfg)
	conversationServiceI := provideConversationUsecase(conversationQueryRepoI, conversationCommandRepoI, memberCmdRepoI, memberQueryRepoI, userGrpcClient, managerTxn, chatEventPublisherI)
	conversationHandler := v1.InitConversationHandler(conversationServiceI)
	userProfileCacheI := redis2.InitUserProfileCache(redisClient)
	memberServiceI := member2.InitMemberUsecase(memberQueryRepoI, userProfileCacheI, userGrpcClient)
	memberHandler := v1.InitMemberHandler(memberServiceI)
	messageQueryRepoI := message.InitMessageQueryRepo(readDb, writeDb)
	messageCmdRepoI := message.InitMessageCmdRepo(readDb, writeDb)
	messageListCacheI := redis2.InitMessageListCache(redisClient)
	wsPublisherI := redis2.InitWsPublisher(redisClient)
	assistantEventPublisherI := kafka.InitAssistantEventPublisher(appCfg)
	messageServiceI := provideMessageUsecase(conversationQueryRepoI, memberQueryRepoI, messageQueryRepoI, messageCmdRepoI, messageListCacheI, wsPublisherI, assistantEventPublisherI)
	messageHandler := v1.InitMessageHandler(messageServiceI)
	wsSubscriberI := redis2.InitWsSubscriber(redisClient)
	hub := ws.NewHub(wsSubscriberI)
	messageRateLimiterI := redis2.InitMessageRateLimiter(redisClient, appCfg)
	jwkCacheRepo := redis2.InitJWKCacheRepo(redisClient)
	tokenDenylistI := redis2.InitRedisDenylist(redisClient)
	server := http.NewServer(appCfg, conversationHandler, memberHandler, messageHandler, hub, messageRateLimiterI, jwkCacheRepo, userGrpcClient, tokenDenylistI)
	grpcServer := grpc.NewServer(appCfg)
	cronServer := cron.NewServer(appCfg)
	userEventHandler := conversation2.InitUserEventHandler(conversationServiceI, messageServiceI)
	logger := provideLogger(appCfg)
	userEventConsumer := worker.InitUserEventConsumer(appCfg, userEventHandler, logger)
	chatEventHandler := conversation2.InitChatEventHandler(conversationQueryRepoI, conversationCommandRepoI, messageServiceI)
	chatEventConsumer := worker.InitChatEventConsumer(appCfg, chatEventHandler, logger)
	assistantResponseConsumer := worker.InitAssistantResponseConsumer(appCfg, messageServiceI, logger)
	apiContainer := api.NewApiContainer(server, grpcServer, cronServer, userEventConsumer, chatEventConsumer, assistantResponseConsumer)
	return apiContainer
}

// wire.go:

var container = wire.NewSet(api.NewApiContainer)

var apiSet = wire.NewSet(cron.NewServer, grpc.NewServer, http.NewServer)

var handlerSet = wire.NewSet(v1.InitConversationHandler, v1.InitMemberHandler, v1.InitMessageHandler)

var serviceSet = wire.NewSet(
	provideConversationUsecase, member2.InitMemberUsecase, provideMessageUsecase, conversation2.InitUserEventHandler, conversation2.InitChatEventHandler,
)

var repoSet = wire.NewSet(conversation.InitConversationCommandRepo, conversation.InitConversationQueryRepo, member.InitMemberCommandRepo, member.InitMemberQueryRepo, message.InitMessageCmdRepo, message.InitMessageQueryRepo, redis2.InitJWKCacheRepo, redis2.InitRedisDenylist, redis2.InitMessageRateLimiter, redis2.InitMessageListCache, redis2.InitUserProfileCache, redis2.InitWsPublisher, redis2.InitWsSubscriber, kafka.InitAssistantEventPublisher, kafka.InitChatEventPublisher)

var providerSet = wire.NewSet(user_grpc.NewGrpcClient, transaction.InitManagerTxn, ws.NewHub, worker.InitUserEventConsumer, worker.InitChatEventConsumer, worker.InitAssistantResponseConsumer, provideLogger)

func provideLogger(cfg *config.AppConfig) logger.Logger {
	return logger.NewZapLogger(cfg.Logger.LogLevel)
}

func provideMessageUsecase(
	conversationQuery interfaces.ConversationQueryRepoI,
	memberQuery interfaces.MemberQueryRepoI,
	messageQuery interfaces.MessageQueryRepoI,
	messageCommand interfaces.MessageCmdRepoI,
	messageListCache interfaces.MessageListCacheI,
	wsPublisher interfaces.WsPublisherI,
	assistantPublisher interfaces.AssistantEventPublisherI,
) interfaces.MessageServiceI {
	return message2.InitMessageUsecase(
		conversationQuery,
		memberQuery,
		messageQuery,
		messageCommand,
		messageListCache,
		wsPublisher,
		assistantPublisher,
	)
}

func provideConversationUsecase(
	conversationReadRepo interfaces.ConversationQueryRepoI,
	conversationCmdRepo interfaces.ConversationCommandRepoI,
	memberCmdRepo interfaces.MemberCmdRepoI,
	memberQueryRepo interfaces.MemberQueryRepoI,
	userGrpcClient user_grpc.UserGrpcClient,
	txn *transaction.ManagerTxn,
	chatEventPublisher interfaces.ChatEventPublisherI,
) interfaces.ConversationServiceI {
	return conversation2.InitConversationUsecase(
		conversationReadRepo,
		conversationCmdRepo,
		memberCmdRepo,
		memberQueryRepo,
		userGrpcClient,
		txn,
		chatEventPublisher,
	)
}
