package grpc

import (
	"context"

	userstatuspb "github.com/vucongthanh92/courier/shared/grpc/user-service/user_status/gen"
	"github.com/vucongthanh92/courier/user-service/helper/constants"
	"github.com/vucongthanh92/courier/user-service/internal/domain/interfaces"
	"github.com/vucongthanh92/courier/user-service/internal/domain/models"
	cacheRepo "github.com/vucongthanh92/courier/user-service/internal/repository/external/redis"
	jwkpb "github.com/vucongthanh92/courier/user-service/pkg/grpc/gen"
)

type GrpcUsecase struct {
	// JWK service state and dependencies.
	jwkpb.UnimplementedJWKServiceServer
	jwkRepo  interfaces.JWKQueryRepoI
	jwkCache cacheRepo.JWKCacheRepo

	// User status service state and dependencies.
	userstatuspb.UnimplementedUserStatusServiceServer
	userRepo interfaces.UserQueryRepoI
}

// NewGrpcUsecase wires all gRPC handlers handled by user-service.
func NewGrpcUsecase(
	jwkRepo interfaces.JWKQueryRepoI,
	jwkCache cacheRepo.JWKCacheRepo,
	userRepo interfaces.UserQueryRepoI,
) *GrpcUsecase {
	return &GrpcUsecase{
		jwkRepo:  jwkRepo,
		jwkCache: jwkCache,
		userRepo: userRepo,
	}
}

// GetPublicKey implements the JWKServiceServer interface generated by gRPC.
func (s *GrpcUsecase) GetPublicKey(ctx context.Context, req *jwkpb.GetPublicKeyRequest) (*jwkpb.GetPublicKeyResponse, error) {
	kid := req.Kid
	if kid == "" {
		active, commonErr := s.jwkRepo.GetActiveKey(ctx)
		if commonErr != nil {
			return nil, commonErr.LogError
		}
		kid = active.Kid
	}

	var entry *models.JWKCacheEntry
	if s.jwkCache != nil {
		entry, _ = s.jwkCache.GetByKid(ctx, kid)
	}
	if entry != nil {
		return &jwkpb.GetPublicKeyResponse{
			Kid:       entry.Kid,
			PublicPem: entry.PublicPEM,
			Alg:       entry.Alg,
		}, nil
	}

	key, commonErr := s.jwkRepo.GetKeyByKid(ctx, kid)
	if commonErr != nil {
		return nil, commonErr.LogError
	}
	if s.jwkCache != nil {
		_ = s.jwkCache.SetByKid(ctx, models.JWKCacheEntry{Kid: key.Kid, PublicPEM: key.PublicPEM, Alg: key.Alg}, constants.Time_Cache_5_minutes)
	}
	return &jwkpb.GetPublicKeyResponse{
		Kid:       key.Kid,
		PublicPem: key.PublicPEM,
		Alg:       key.Alg,
	}, nil
}

// CheckUsersStatus implements the UserStatusServiceServer interface generated by gRPC.
func (s *GrpcUsecase) CheckUsersStatus(ctx context.Context, req *userstatuspb.CheckUsersStatusRequest) (*userstatuspb.CheckUsersStatusResponse, error) {
	users, commonErr := s.userRepo.GetUsersByIDs(ctx, req.UserIds)
	if commonErr != nil {
		return nil, commonErr.LogError
	}

	userMap := make(map[uint64]string, len(users))
	items := make([]*userstatuspb.UserStatusItem, 0, len(users))
	for _, user := range users {
		userMap[user.ID] = user.Status
		items = append(items, &userstatuspb.UserStatusItem{
			UserId: user.ID,
			Status: user.Status,
		})
	}

	invalidUserIDs := make([]uint64, 0)
	for _, userID := range req.UserIds {
		status, ok := userMap[userID]
		if !ok || status != constants.UserStatusVerified {
			invalidUserIDs = append(invalidUserIDs, userID)
		}
	}

	return &userstatuspb.CheckUsersStatusResponse{
		Items:          items,
		InvalidUserIds: invalidUserIDs,
		AllVerified:    len(invalidUserIDs) == 0,
	}, nil
}
