package grpc

import (
	"context"

	"github.com/vucongthanh92/courier/user-service/helper/constants"
	"github.com/vucongthanh92/courier/user-service/internal/domain/interfaces"
	"github.com/vucongthanh92/courier/user-service/internal/domain/models"
	cacheRepo "github.com/vucongthanh92/courier/user-service/internal/repository/external/redis"
	jwkpb "github.com/vucongthanh92/courier/user-service/pkg/grpc/gen"
)

type JWKServer struct {
	jwkpb.UnimplementedJWKServiceServer
	jwkRepo  interfaces.JWKQueryRepoI
	jwkCache cacheRepo.JWKCacheRepo
}

func NewJWKServer(jwkRepo interfaces.JWKQueryRepoI, jwkCache cacheRepo.JWKCacheRepo) *JWKServer {
	return &JWKServer{
		jwkRepo:  jwkRepo,
		jwkCache: jwkCache,
	}
}

// JWKServer implements the JWKServiceServer interface generated by gRPC.
func (s *JWKServer) GetPublicKey(ctx context.Context, req *jwkpb.GetPublicKeyRequest) (*jwkpb.GetPublicKeyResponse, error) {
	kid := req.Kid
	if kid == "" {
		active, commonErr := s.jwkRepo.GetActiveKey(ctx)
		if commonErr != nil {
			return nil, commonErr.LogError
		}
		kid = active.Kid
	}

	var entry *models.JWKCacheEntry
	if s.jwkCache != nil {
		entry, _ = s.jwkCache.GetByKid(ctx, kid)
	}
	if entry != nil {
		return &jwkpb.GetPublicKeyResponse{
			Kid:       entry.Kid,
			PublicPem: entry.PublicPEM,
			Alg:       entry.Alg,
		}, nil
	}

	key, commonErr := s.jwkRepo.GetKeyByKid(ctx, kid)
	if commonErr != nil {
		return nil, commonErr.LogError
	}
	if s.jwkCache != nil {
		_ = s.jwkCache.SetByKid(ctx, models.JWKCacheEntry{Kid: key.Kid, PublicPEM: key.PublicPEM, Alg: key.Alg}, constants.Time_Cache_5_minutes)
	}
	return &jwkpb.GetPublicKeyResponse{
		Kid:       key.Kid,
		PublicPem: key.PublicPEM,
		Alg:       key.Alg,
	}, nil
}
