auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

limits_config:
  ingestion_rate_mb: 4
  max_query_length: 1h
  max_query_parallelism: 4
  max_query_lookback: 168h
  allow_structured_metadata: false

query_range:
  align_queries_with_step: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h

compactor:
  working_directory: /loki/compactor
