// Code generated by protoc-gen-go. DO NOT EDIT.

package jwkpb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache

	Kid string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
}

func (x *GetPublicKeyRequest) Reset()         { *x = GetPublicKeyRequest{} }
func (x *GetPublicKeyRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetPublicKeyRequest) ProtoMessage()    {}
func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jwk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache

	Kid       string `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	PublicPem string `protobuf:"bytes,2,opt,name=public_pem,json=publicPem,proto3" json:"public_pem,omitempty"`
	Alg       string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
}

func (x *GetPublicKeyResponse) Reset()         { *x = GetPublicKeyResponse{} }
func (x *GetPublicKeyResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (*GetPublicKeyResponse) ProtoMessage()    {}
func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_jwk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var File_jwk_proto protoreflect.FileDescriptor

var file_jwk_proto_rawDesc = []byte{}

var (
	file_jwk_proto_rawDescOnce sync.Once
	file_jwk_proto_rawDescData = file_jwk_proto_rawDesc
)

func file_jwk_proto_rawDescGZIP() []byte {
	file_jwk_proto_rawDescOnce.Do(func() {
		file_jwk_proto_rawDescData = protoimpl.X.CompressGZIP(file_jwk_proto_rawDescData)
	})
	return file_jwk_proto_rawDescData
}

var file_jwk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_jwk_proto_goTypes = []interface{}{
	(*GetPublicKeyRequest)(nil),
	(*GetPublicKeyResponse)(nil),
}
var file_jwk_proto_depIdxs = []int32{}

func init() { file_jwk_proto_init() }

func file_jwk_proto_init() {
	if File_jwk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_jwk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jwk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPublicKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jwk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:    2,
			NumExtensions:  0,
			NumServices:    1,
		},
		GoTypes:           file_jwk_proto_goTypes,
		DependencyIndexes: file_jwk_proto_depIdxs,
		MessageInfos:      file_jwk_proto_msgTypes,
	}.Build()
	File_jwk_proto = out.File
	file_jwk_proto_rawDesc = nil
	file_jwk_proto_goTypes = nil
	file_jwk_proto_depIdxs = nil
}
