// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package jwkpb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion9

type JWKServiceClient interface {
	GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error)
}

type jWKServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJWKServiceClient(cc grpc.ClientConnInterface) JWKServiceClient {
	return &jWKServiceClient{cc}
}

func (c *jWKServiceClient) GetPublicKey(ctx context.Context, in *GetPublicKeyRequest, opts ...grpc.CallOption) (*GetPublicKeyResponse, error) {
	out := new(GetPublicKeyResponse)
	err := c.cc.Invoke(ctx, "/jwk.v1.JWKService/GetPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type JWKServiceServer interface {
	GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error)
	mustEmbedUnimplementedJWKServiceServer()
}

type UnimplementedJWKServiceServer struct{}

func (UnimplementedJWKServiceServer) GetPublicKey(context.Context, *GetPublicKeyRequest) (*GetPublicKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedJWKServiceServer) mustEmbedUnimplementedJWKServiceServer() {}

type UnsafeJWKServiceServer interface {
	mustEmbedUnimplementedJWKServiceServer()
}

func RegisterJWKServiceServer(s grpc.ServiceRegistrar, srv JWKServiceServer) {
	s.RegisterService(&JWKService_ServiceDesc, srv)
}

func _JWKService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWKServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwk.v1.JWKService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWKServiceServer).GetPublicKey(ctx, req.(*GetPublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var JWKService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jwk.v1.JWKService",
	HandlerType: (*JWKServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _JWKService_GetPublicKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwk.proto",
}
