// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/conversation/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "create new conversation",
                "parameters": [
                    {
                        "description": "CreateConversationRequest",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateConversationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CreateConversationResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/conversation/{id}/members": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "list members for a conversation with resolved user profiles",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-models_ListConversationMembersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/conversations": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Conversation"
                ],
                "summary": "list conversations for authenticated user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Limit, default 20 and max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor activity timestamp",
                        "name": "before_last_message_at",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Cursor conversation ID",
                        "name": "before_conversation_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-models_ListConversationsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/conversations/{id}/messages": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "list messages in a conversation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Limit, default 20 and max 100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Fetch messages older than this message ID",
                        "name": "before_message_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-models_ListMessagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/conversations/{id}/messages/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "create a text message in a conversation",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Conversation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "SendMessageRequest",
                        "name": "params",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-models_MessageResponse"
                        }
                    },
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-models_MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/httpcommon.SuccessResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.ConversationMember": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "joined_at": {
                    "type": "string"
                },
                "last_read_at": {
                    "type": "string"
                },
                "last_read_message_id": {
                    "type": "integer"
                },
                "left_at": {
                    "type": "string"
                },
                "muted_until": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "httpcommon.SuccessResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDTO"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "httpcommon.SuccessResponse-models_ListConversationMembersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.ListConversationMembersResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDTO"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "httpcommon.SuccessResponse-models_ListConversationsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.ListConversationsResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDTO"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "httpcommon.SuccessResponse-models_ListMessagesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.ListMessagesResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDTO"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "httpcommon.SuccessResponse-models_MessageResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.MessageResponse"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ErrorDTO"
                    }
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "models.ConversationListResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string",
                    "example": "0"
                },
                "direct_key": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "last_message": {
                    "$ref": "#/definitions/models.MessageResponse"
                },
                "last_message_at": {
                    "type": "string"
                },
                "last_message_id": {
                    "type": "string",
                    "example": "0"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ConversationMemberResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "0"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "joined_at": {
                    "type": "string"
                },
                "last_read_at": {
                    "type": "string"
                },
                "last_read_message_id": {
                    "type": "string",
                    "example": "0"
                },
                "left_at": {
                    "type": "string"
                },
                "muted_until": {
                    "type": "string"
                },
                "profile": {
                    "$ref": "#/definitions/models.UserProfileSummaryResponse"
                },
                "role": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.CreateConversationRequest": {
            "type": "object",
            "required": [
                "member_user_ids",
                "type"
            ],
            "properties": {
                "creatorID": {
                    "type": "integer"
                },
                "member_user_ids": {
                    "type": "array",
                    "minItems": 2,
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "direct",
                        "group"
                    ]
                }
            }
        },
        "models.CreateConversationResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string",
                    "example": "0"
                },
                "direct_key": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "last_message_at": {
                    "type": "string"
                },
                "last_message_id": {
                    "type": "string",
                    "example": "0"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.ConversationMember"
                    }
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ErrorDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ListConversationMembersResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "0"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConversationMemberResponse"
                    }
                }
            }
        },
        "models.ListConversationsPaginationResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_before_conversation_id": {
                    "type": "string",
                    "example": "0"
                },
                "next_before_last_message_at": {
                    "type": "string"
                }
            }
        },
        "models.ListConversationsResponse": {
            "type": "object",
            "properties": {
                "conversations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConversationListResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/models.ListConversationsPaginationResponse"
                }
            }
        },
        "models.ListMessagesResponse": {
            "type": "object",
            "properties": {
                "conversation_id": {
                    "type": "string",
                    "example": "0"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ConversationMemberResponse"
                    }
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.MessageResponse"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/models.MessagePaginationResponse"
                }
            }
        },
        "models.MessagePaginationResponse": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                },
                "next_before_message_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "body": {
                    "type": "string"
                },
                "client_message_id": {
                    "type": "string"
                },
                "conversation_id": {
                    "type": "string",
                    "example": "0"
                },
                "created_at": {
                    "type": "string"
                },
                "edited_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "0"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "reply_to_message_id": {
                    "type": "string",
                    "example": "0"
                },
                "sender_id": {
                    "type": "string",
                    "example": "0"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.SendMessageRequest": {
            "type": "object",
            "required": [
                "body",
                "type"
            ],
            "properties": {
                "body": {
                    "type": "string"
                },
                "client_message_id": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "reply_to_message_id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.UserProfileSummaryResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string",
                    "example": "0"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Courier Chat Service API",
	Description:      "Conversation and messaging APIs for Courier.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
