// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"context"
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/vucongthanh92/courier/user-service/config"
	"github.com/vucongthanh92/courier/user-service/database"
	"github.com/vucongthanh92/courier/user-service/helper/transaction"
	"github.com/vucongthanh92/courier/user-service/internal/api"
	"github.com/vucongthanh92/courier/user-service/internal/api/cron"
	"github.com/vucongthanh92/courier/user-service/internal/api/grpc"
	"github.com/vucongthanh92/courier/user-service/internal/api/http"
	"github.com/vucongthanh92/courier/user-service/internal/api/http/v1"
	"github.com/vucongthanh92/courier/user-service/internal/domain/interfaces"
	"github.com/vucongthanh92/courier/user-service/internal/repository/external/email_sender"
	"github.com/vucongthanh92/courier/user-service/internal/repository/external/jwt"
	"github.com/vucongthanh92/courier/user-service/internal/repository/external/oauth"
	redis2 "github.com/vucongthanh92/courier/user-service/internal/repository/external/redis"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/audit_log"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/auth_credential"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/email_verification"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/identity"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/jwk"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/outbox"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/refresh_token"
	"github.com/vucongthanh92/courier/user-service/internal/repository/persistent/user"
	"github.com/vucongthanh92/courier/user-service/internal/usecase/audit_log"
	"github.com/vucongthanh92/courier/user-service/internal/usecase/authen"
	"github.com/vucongthanh92/courier/user-service/internal/usecase/credential"
	"github.com/vucongthanh92/courier/user-service/internal/usecase/cronjob"
	identity2 "github.com/vucongthanh92/courier/user-service/internal/usecase/identity"
	outbox2 "github.com/vucongthanh92/courier/user-service/internal/usecase/outbox"
	"github.com/vucongthanh92/courier/user-service/internal/usecase/token"
	"github.com/vucongthanh92/courier/user-service/internal/worker"
	"github.com/vucongthanh92/courier/user-service/redis"
	"github.com/vucongthanh92/go-base-utils/logger"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitializeContainer(appCfg *config.AppConfig, readDb *database.GormReadDb, writeDb *database.GormWriteDb, redisClient redis.Client) *api.ApiContainer {
	managerTxn := transaction.InitManagerTxn(writeDb)
	auditLogCommandRepoI := auditlog.InitAuditLogCmdRepository(writeDb)
	auditLogServiceI := auditlog_uc.InitAuditLogUsecase(auditLogCommandRepoI)
	outboxCommandRepoI := outbox.InitOutboxCmdRepository(writeDb)
	outboxQueryRepoI := outbox.InitOutboxQueryRepository(readDb)
	outboxServiceI := outbox2.InitOutboxUsecase(auditLogServiceI, outboxCommandRepoI, outboxQueryRepoI)
	userQueryRepoI := user.InitUserQueryRepository(readDb)
	userCommandRepoI := user.InitUserCmdRepository(writeDb)
	authCredentialCommandRepoI := authcredential.InitAuthCredentialCmdRepository(writeDb)
	authCredentialQueryRepoI := authcredential.InitAuthCredentialQueryRepository(readDb)
	emailVerificationCommandRepoI := emailverification.InitEmailVerificationCmdRepository(writeDb)
	emailVerificationQueryRepoI := emailverification.InitEmailVerificationQueryRepository(readDb)
	refreshTokenQueryRepoI := refreshtoken.InitRefreshTokenQueryRepository(readDb)
	jwkQueryRepoI := jwk.InitJWKQueryRepository(readDb)
	logger := provideLogger(appCfg)
	jwtSignerI := provideJWTSigner(jwkQueryRepoI, logger)
	refreshTokenCommandRepoI := refreshtoken.InitRefreshTokenCmdRepository(writeDb)
	tokenDenylistI := redis2.InitRedisDenylist(redisClient)
	tokenUseCaseI := token.InitTokenUseCase(managerTxn, auditLogServiceI, jwtSignerI, refreshTokenCommandRepoI, tokenDenylistI)
	authServiceI := authen.InitAuthUseCase(managerTxn, auditLogServiceI, outboxServiceI, userQueryRepoI, userCommandRepoI, authCredentialCommandRepoI, authCredentialQueryRepoI, emailVerificationCommandRepoI, emailVerificationQueryRepoI, refreshTokenQueryRepoI, tokenUseCaseI)
	authHandler := v1.InitAuthHandler(authServiceI)
	identityCommandRepoI := identity.InitIdentityCmdRepository(writeDb)
	identityQueryRepoI := identity.InitIdentityQueryRepository(readDb)
	googleProviderClient := provideGoogleClient(appCfg)
	githubProviderClient := provideGitHubClient(appCfg)
	identityUseCaseI := identity2.InitIdentityUseCase(managerTxn, auditLogServiceI, userQueryRepoI, userCommandRepoI, identityCommandRepoI, identityQueryRepoI, googleProviderClient, githubProviderClient, authCredentialCommandRepoI, authCredentialQueryRepoI, tokenUseCaseI)
	identityHandler := v1.InitIdentityHandler(identityUseCaseI)
	authCredentialServiceI := credential.InitCredentialUseCase(managerTxn, auditLogServiceI, outboxServiceI, userQueryRepoI, userCommandRepoI, authCredentialCommandRepoI, authCredentialQueryRepoI, emailVerificationCommandRepoI, emailVerificationQueryRepoI, refreshTokenQueryRepoI, tokenUseCaseI)
	credentialHandler := v1.InitCredentialHandler(authCredentialServiceI)
	server := http.NewServer(appCfg, authHandler, identityHandler, credentialHandler, jwkQueryRepoI, tokenDenylistI)
	grpcServer := grpc.NewServer(appCfg)
	cronJobServiceI := cronjob.NewCronJobService(refreshTokenCommandRepoI)
	cronServer := cron.NewServer(appCfg, cronJobServiceI)
	pool := newPgxPool(appCfg)
	emailConfig := provideEmailConfig(appCfg)
	emailSenderI := emailsender.InitSMTPSender(emailConfig, logger)
	outboxWorker := worker.InitOutboxWorker(pool, outboxQueryRepoI, outboxCommandRepoI, auditLogServiceI, emailSenderI, logger)
	apiContainer := api.NewApiContainer(server, grpcServer, cronServer, outboxWorker)
	return apiContainer
}

// wire.go:

var workerSet = wire.NewSet(worker.InitOutboxWorker, newPgxPool)

var container = wire.NewSet(api.NewApiContainer)

var apiSet = wire.NewSet(cron.NewServer, grpc.NewServer, http.NewServer)

var handlerSet = wire.NewSet(v1.InitIdentityHandler, v1.InitAuthHandler, v1.InitCredentialHandler)

var serviceSet = wire.NewSet(cronjob.NewCronJobService, auditlog_uc.InitAuditLogUsecase, authen.InitAuthUseCase, identity2.InitIdentityUseCase, outbox2.InitOutboxUsecase, token.InitTokenUseCase, credential.InitCredentialUseCase)

var repoSet = wire.NewSet(transaction.InitManagerTxn, user.InitUserCmdRepository, user.InitUserQueryRepository, identity.InitIdentityCmdRepository, identity.InitIdentityQueryRepository, auditlog.InitAuditLogCmdRepository, authcredential.InitAuthCredentialCmdRepository, authcredential.InitAuthCredentialQueryRepository, emailverification.InitEmailVerificationCmdRepository, emailverification.InitEmailVerificationQueryRepository, outbox.InitOutboxCmdRepository, outbox.InitOutboxQueryRepository, refreshtoken.InitRefreshTokenCmdRepository, refreshtoken.InitRefreshTokenQueryRepository, jwk.InitJWKQueryRepository, emailsender.InitSMTPSender, redis2.InitRedisDenylist, provideEmailConfig,
	provideLogger,
	provideJWTSigner,
	provideGoogleClient,
	provideGitHubClient,
)

// ================= extra functions for implement interface =================
// newPgxPool initializes a pgx pool with connection string from config.
func newPgxPool(cfg *config.AppConfig) *pgxpool.Pool {
	pool, err := pgxpool.New(context.Background(), cfg.Database.WriteDbCfg.ConnectionString)
	if err != nil {
		logger.Fatal("cannot init pgxpool", zap.Error(err))
	}
	return pool
}

// provideEmailConfig returns the nested email config for DI.
func provideEmailConfig(cfg *config.AppConfig) *config.EmailConfig {
	return cfg.Email
}

// provideLogger initializes a zap logger with configured level.
func provideLogger(cfg *config.AppConfig) logger.Logger {
	return logger.NewZapLogger(cfg.Logger.LogLevel)
}

// provideJWTSigner initializes the JWT signer with RSA keys from config.
func provideJWTSigner(jwkRepo interfaces.JWKQueryRepoI, log logger.Logger) interfaces.JWTSignerI {
	jwk2, err := jwkRepo.GetActiveKey(context.Background())
	if err != nil {
		log.Fatal("load active jwk failed", zap.Any("error", err))
	}
	s, err2 := jwt.InitJWTSigner(jwk2, log)
	if err2 != nil {
		log.Fatal("init jwt signer failed", zap.Error(err2))
	}
	return s
}

// provideGoogleClient initializes the Google OAuth client with credentials from config.
func provideGoogleClient(cfg *config.AppConfig) interfaces.GoogleProviderClient {
	return oauth.NewGoogleClient(
		cfg.OAuth.Google.ClientID,
		cfg.OAuth.Google.ClientID,
		cfg.OAuth.Google.ClientSecret,
		cfg.OAuth.Google.RedirectURI,
	)
}

// provideGitHubClient initializes the GitHub OAuth client with API base URL from config.
func provideGitHubClient(cfg *config.AppConfig) interfaces.GithubProviderClient {
	return oauth.NewGitHubClient(
		cfg.OAuth.Github.APIBase,
		cfg.OAuth.Github.ClientID,
		cfg.OAuth.Github.ClientSecret,
	)
}
