// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/vucongthanh92/courier/payment-gateway/config"
	"github.com/vucongthanh92/courier/payment-gateway/database"
	"github.com/vucongthanh92/courier/payment-gateway/helper/transaction"
	"github.com/vucongthanh92/courier/payment-gateway/internal/api"
	"github.com/vucongthanh92/courier/payment-gateway/internal/api/grpc"
	"github.com/vucongthanh92/courier/payment-gateway/internal/api/http"
	"github.com/vucongthanh92/courier/payment-gateway/internal/api/http/v1"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/external/providers"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/external/providers/sepay"
	redis2 "github.com/vucongthanh92/courier/payment-gateway/internal/repository/external/redis"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/external/user_grpc"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/idempotency"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/ledger"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/outbox"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/provider_event"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/topup"
	"github.com/vucongthanh92/courier/payment-gateway/internal/repository/persistent/wallet"
	idempotency2 "github.com/vucongthanh92/courier/payment-gateway/internal/usecase/idempotency"
	topup2 "github.com/vucongthanh92/courier/payment-gateway/internal/usecase/topup"
	wallet2 "github.com/vucongthanh92/courier/payment-gateway/internal/usecase/wallet"
	"github.com/vucongthanh92/courier/payment-gateway/internal/usecase/webhook"
	"github.com/vucongthanh92/courier/payment-gateway/redis"
)

// Injectors from wire.go:

func InitializeContainer(cfg *config.AppConfig, readDB *database.GormReadDb, writeDB *database.GormWriteDb, redisClient redis.Client) *api.ApiContainer {
	managerTxn := transaction.InitManagerTxn(writeDB)
	walletQueryRepoI := wallet.InitWalletQueryRepository(readDB)
	walletCommandRepoI := wallet.InitWalletCmdRepository(writeDB)
	walletServiceI := wallet2.InitWalletUsecase(walletQueryRepoI, walletCommandRepoI)
	topUpCommandRepoI := topup.InitTopUpCmdRepository(writeDB)
	idempotencyCommandRepoI := idempotency.InitIdempotencyCmdRepository(writeDB)
	idempotencyServiceI := idempotency2.InitIdempotencyUsecase(idempotencyCommandRepoI)
	sePayConfig := provideSePayConfig(cfg)
	provider := sepay.New(sePayConfig)
	paymentGatewayResolverI := providers.InitPaymentGatewayResolver(provider)
	topUpServiceI := topup2.InitTopUpUsecase(managerTxn, walletServiceI, topUpCommandRepoI, idempotencyServiceI, paymentGatewayResolverI)
	topUpHandler := v1.InitTopUpHandler(topUpServiceI)
	providerEventCommandRepoI := provider_event.InitProviderEventCmdRepository(writeDB)
	topUpQueryRepoI := topup.InitTopUpQueryRepository(readDB)
	ledgerQueryRepoI := ledger.InitLedgerQueryRepository(readDB)
	ledgerCommandRepoI := ledger.InitLedgerCmdRepository(writeDB)
	outboxCommandRepoI := outbox.InitOutboxCmdRepository(writeDB)
	sePayWebhookServiceI := webhook.InitSePayWebhookUsecase(managerTxn, provider, providerEventCommandRepoI, topUpQueryRepoI, topUpCommandRepoI, walletCommandRepoI, ledgerQueryRepoI, ledgerCommandRepoI, outboxCommandRepoI)
	sePayWebhookHandler := v1.InitSePayWebhookHandler(provider, sePayWebhookServiceI)
	jwkCacheRepo := redis2.InitJWKCacheRepo(redisClient)
	userGrpcClient := user_grpc.NewGrpcClient(cfg)
	tokenDenylistI := redis2.InitRedisDenylist(redisClient)
	server := http.NewServer(cfg, topUpHandler, sePayWebhookHandler, jwkCacheRepo, userGrpcClient, tokenDenylistI)
	grpcServer := grpc.NewServer(cfg)
	apiContainer := api.NewApiContainer(server, grpcServer)
	return apiContainer
}

// wire.go:

var repoSet = wire.NewSet(transaction.InitManagerTxn, wallet.InitWalletCmdRepository, wallet.InitWalletQueryRepository, topup.InitTopUpCmdRepository, topup.InitTopUpQueryRepository, idempotency.InitIdempotencyCmdRepository, provider_event.InitProviderEventCmdRepository, ledger.InitLedgerCmdRepository, ledger.InitLedgerQueryRepository, outbox.InitOutboxCmdRepository, sepay.New, providers.InitPaymentGatewayResolver, redis2.InitRedisDenylist, redis2.InitJWKCacheRepo, user_grpc.NewGrpcClient)

var serviceSet = wire.NewSet(idempotency2.InitIdempotencyUsecase, wallet2.InitWalletUsecase, topup2.InitTopUpUsecase, webhook.InitSePayWebhookUsecase)

var handlerSet = wire.NewSet(v1.InitTopUpHandler, v1.InitSePayWebhookHandler)

var apiSet = wire.NewSet(http.NewServer, grpc.NewServer, api.NewApiContainer)

func provideSePayConfig(cfg *config.AppConfig) config.SePayConfig { return cfg.SePay }
